server:
  port: 8082

datasource:
  url: jdbc:mysql://localhost:3306/micservicesys?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
  username: root
  password: '123456'
  driverClassName: com.mysql.jdbc.Driver